[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
calltokenthing = "9PEbvRxVa251jgFsmBf6ioQyWNvRBRqdZbwNPzfC7Zev"
simplepred = "HFZ35AHHYBFQEgCEG9VCurzizQQRBxfpoGAdryBPdvhc"
tokenthing = "FY4qYkgfd3VHnfH1g5kDwPTHf8UVG7AUthnGRbEW4HvK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/chiragjani/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
